name: ESP32_S2

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
    
# on:
#   push:
#   pull_request:
#     paths-ignore:
#       - "examples/**"
#       - "README.md"
#       - "ci/*unix*.sh"
#       - ".github/workflows/build_unix.yml"

jobs:
  micropython_esp32_s2_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            path: '.'
      - name: Prepare to Build Micropython Firmware for ESP3_S2
        run: |
          git submodule init
          git submodule update --recursive
          cd micropython
          git submodule update --init lib/axtls
          git submodule update --init lib/berkeley-db-1.xx
          cd ..
      - name: Install ESP-IDF
        run: |
          mkdir -p ~/work/esp
          cd ~/work/esp
          git clone -b v4.4.1 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh esp32s2
          cd ..
          cd ..   
          cd ..
      - name: Build micropython cross compiler
        run: |
          source ~/work/esp/esp-idf/export.sh
          cd ~/work/custom_micropython/custom_micropython/micropython
          echo "make -C mpy-cross V=1 clean all"
          make -C mpy-cross V=1 clean all
      - name: Build ESP32 firmware
        run: |
           echo "source ~/work/esp/esp-idf/export.sh"
           source ~/work/esp/esp-idf/export.sh
           cp -R ~/work/custom_micropython/custom_micropython/boards/esp32/* ~/work/custom_micropython/custom_micropython/micropython/ports/esp32/boards
           cd ~/work/custom_micropython/custom_micropython/micropython/ports/esp32
           ls ~/work/custom_micropython/custom_micropython/micropython/ports/esp32
           source ~/work/esp/esp-idf/export.sh
           echo "idf.py -D MICROPY_BOARD=FRANZININHO_ESP32_S2_WROOM -B ~/build/FRANZININHO_ESP32_S2_WROOM  build"
           idf.py -D MICROPY_BOARD=FRANZININHO_ESP32_S2_WROOM -B ~/build/FRANZININHO_ESP32_S2_WROOM  build
           echo "idf.py -D MICROPY_BOARD=FRANZININHO_WIFI_WROVER -B ~/build/FRANZININHO_WIFI_WROVER  build"
           idf.py -D MICROPY_BOARD=FRANZININHO_WIFI_WROVER -B ~/build/FRANZININHO_WIFI_WROVER  build
      - name: Archive ESP32 FRANZININHO_ESP32_S2_WROOM
        uses: actions/upload-artifact@v2
        with:
          name: FRANZININHO_ESP32_S2_WROOM
          path: |
            ~/build/FRANZININHO_ESP32_S2_WROOM/partition_table/partition-table.bin
            ~/build/FRANZININHO_ESP32_S2_WROOM/bootloader/bootloader.bin
            ~/build/FRANZININHO_ESP32_S2_WROOM/micropython.bin
      - name: Archive ESP32 FRANZININHO_WIFI_WROVER
        uses: actions/upload-artifact@v2
        with:
          name: FRANZININHO_WIFI_WROVER
          path: |
            ~/build/FRANZININHO_WIFI_WROVER/partition_table/partition-table.bin
            ~/build/FRANZININHO_WIFI_WROVER/bootloader/bootloader.bin
            ~/build/FRANZININHO_WIFI_WROVER/micropython.bin
